In [16]:
import pandas as pd
import numpy as np
import random

First we would need some values for mu. We'll use whatever.

In [19]:
# random values for mu
mu = [9, 10 ,11]
mu

[9, 10, 11]

We will also need to generate some matrices for y, and they'll need to contain cells of n number of observation in each cell.

In [15]:
""" generate a matrix of r rows by c columns with o observations per cell between lower and upper """
def spawnMatrix(nRow, nCol, cellSize, cellLower, cellUpper):
    return pd.DataFrame(
        [
            [np.array(list(random.randint(cellLower, cellUpper)
                for i in range(cellSize)))                         
                    for i in range(nRow)
            ]
            for i in range(nCol)
        ]
    ).transpose()

# create values for y using the above function
y = spawnMatrix(nRow = 6, nCol = 6, cellSize = 3, cellLower = 1, cellUpper = 10)

# name the columns for convinience during iteration
y.columns = ["col" + str(i) for i in range(6)]
y

col0         col1        col2         col3        col4        col5
0  [6, 2, 9]   [10, 7, 6]   [6, 5, 2]  [10, 9, 10]   [6, 2, 6]  [8, 10, 3]
1  [1, 9, 6]   [10, 3, 4]   [8, 6, 6]    [1, 8, 1]  [1, 3, 10]  [9, 10, 3]
2  [2, 6, 5]  [10, 10, 9]   [5, 5, 7]    [5, 4, 4]   [2, 4, 8]  [10, 7, 4]
3  [8, 9, 8]   [4, 4, 10]  [4, 10, 8]    [8, 3, 3]  [2, 10, 4]  [3, 6, 10]
4  [2, 3, 8]    [5, 5, 2]   [2, 5, 3]    [4, 5, 9]   [1, 8, 7]   [4, 9, 2]
5  [5, 3, 4]   [3, 10, 2]  [1, 8, 10]    [7, 9, 5]   [7, 5, 2]   [5, 3, 7]

We now have a 6x6 matrix or cells the each contain 3 values. This will be easier; we can just frame some lists.

In [8]:
# create a design matrix (from the notes)
designMatrix = pd.DataFrame(
    [
        np.array([1, 1, 1, 1, 1, 1]),
        np.array([1, 1, 0, 0, -1, -1]),
        np.array([0, 0, 1, 1, -1, -1])
    ]
).transpose()

# inspect to make sure it is ok
print(designMatrix.values)

[[ 1  1  0]
 [ 1  1  0]
 [ 1  0  1]
 [ 1  0  1]
 [ 1 -1 -1]
 [ 1 -1 -1]]


This looks likes the design matrix presented in the notes.

In [22]:
print("The matrix transposed is:\n", designMatrix.transpose().values, "\n")

for row in y.itertuples():
    print("The y value is:", row.col0)
    print("The product with the matrix is:", np.dot(row.col0, designMatrix.transpose()), "\n")

The matrix transposed is:
 [[ 1  1  1  1  1  1]
 [ 1  1  0  0 -1 -1]
 [ 0  0  1  1 -1 -1]] 

The y value is: [6 2 9]
The product with the matrix is: [ 8  8 15 15 -5 -5] 

The y value is: [1 9 6]
The product with the matrix is: [ 10  10   7   7 -14 -14] 

The y value is: [2 6 5]
The product with the matrix is: [ 8  8  7  7 -9 -9] 

The y value is: [8 9 8]
The product with the matrix is: [17 17 16 16 -9 -9] 

The y value is: [2 3 8]
The product with the matrix is: [ 5  5 10 10 -9 -9] 

The y value is: [5 3 4]
The product with the matrix is: [ 8  8  9  9 -2 -2] 

