Let's say we trying to implement this:

$y_{i} = \beta_{0} + \beta I_\{{_2}_\} + \epsilon_i , \sim^{iid}N(0,\sigma^2)$

In [1]:
import pandas as pd
import numpy as np
import random

First we would need some values for mu. We'll use whatever.

In [2]:
# random values for mu
mu = [9, 10, 11]
mu

[9, 10, 11]

We now have a 6x6 matrix or cells the each contain 3 values. Next we can make a design matrix. This will be easier; we can just frame some lists.

In [3]:
# create a design matrix (from the notes)
designMatrix = pd.DataFrame(
    [
        np.array([1, 1, 0, 0, 0, 0]),
        np.array([0, 0, 1, 1, 0, 0]),
        np.array([0, 0, 0, 0, 1, 1])
    ]
).transpose()

# inspect to make sure it is ok
print(designMatrix.values)

[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]


This looks likes the design matrix presented in the notes. Now to make the errors.

In [4]:
# we will use random decimal values between -1, 1
def errors(number):
    return [np.random.uniform(-1,1,1)[0] for i in range(number)]

err = errors(6)

Now we can compute y.

In [9]:
# multiply the matrices, add the error
np.dot(designMatrix, mu) + err

array([ 9.45839282,  8.36023557,  9.18941102, 10.72625479, 11.98403989,
       10.41256581])

### Misc - might need this later

In [6]:
""" generate a matrix of r rows by c columns with o observations per cell between lower and upper """
def spawnMatrix(nRow, nCol, cellSize, cellLower, cellUpper):
    return pd.DataFrame(
        [
            [np.array(list(random.randint(cellLower, cellUpper)
                for i in range(cellSize)))                         
                    for i in range(nRow)
            ]
            for i in range(nCol)
        ]
    ).transpose()

# create values for y using the above function
y = spawnMatrix(nRow = 6, nCol = 6, cellSize = 3, cellLower = 1, cellUpper = 10)

# name the columns for convinience during iteration
y.columns = ["col" + str(i) for i in range(6)]

print("The matrix for y\n", y, "\n")

print("The design matrix transposed is:\n", designMatrix.transpose().values, "\n")
for row in y.itertuples():
    print("The y value is:", row.col0)
    print("The product with the matrix is:", np.dot(row.col0, designMatrix.transpose()), "\n")

The matrix for y
           col0        col1       col2       col3        col4        col5
0  [10, 10, 7]   [9, 4, 9]  [4, 9, 5]  [5, 6, 3]  [10, 1, 9]   [8, 9, 2]
1    [4, 3, 9]   [1, 5, 6]  [8, 7, 5]  [6, 9, 9]   [1, 9, 7]   [6, 7, 8]
2    [2, 6, 6]   [7, 6, 8]  [2, 8, 3]  [4, 4, 9]   [2, 2, 6]   [3, 1, 8]
3   [3, 10, 9]  [2, 10, 3]  [2, 3, 3]  [4, 8, 9]   [4, 5, 9]  [10, 4, 9]
4  [6, 10, 10]   [3, 3, 5]  [5, 5, 6]  [7, 3, 3]   [2, 8, 8]   [9, 7, 8]
5   [10, 7, 7]   [7, 1, 7]  [4, 2, 3]  [1, 9, 9]   [3, 6, 7]   [1, 1, 8] 

The design matrix transposed is:
 [[1 1 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 1 1]] 

The y value is: [10 10  7]
The product with the matrix is: [10 10 10 10  7  7] 

The y value is: [4 3 9]
The product with the matrix is: [4 4 3 3 9 9] 

The y value is: [2 6 6]
The product with the matrix is: [2 2 6 6 6 6] 

The y value is: [ 3 10  9]
The product with the matrix is: [ 3  3 10 10  9  9] 

The y value is: [ 6 10 10]
The product with the matrix is: [ 6  6 10 10 10 10] 

