In [19]:
import pandas as pd
import numpy as np
import random

The formula:

$$y

First we would need some values for mu. We'll use whatever.

In [20]:
# random values for mu
mu = [9, 10, 11]
mu

[9, 10, 11]

We now have a 6x6 matrix or cells the each contain 3 values. Next we can make a design matrix. This will be easier; we can just frame some lists.

In [21]:
# create a design matrix (from the notes)
designMatrix = pd.DataFrame(
    [
        np.array([1, 1, 1, 1, 1, 1]),
        np.array([1, 1, 0, 0, -1, -1]),
        np.array([0, 0, 1, 1, -1, -1])
    ]
).transpose()

# inspect to make sure it is ok
print(designMatrix.values)

[[ 1  1  0]
 [ 1  1  0]
 [ 1  0  1]
 [ 1  0  1]
 [ 1 -1 -1]
 [ 1 -1 -1]]


This looks likes the design matrix presented in the notes. Next up is the errors.

In [22]:
# we will use random decimal values between -1, 1
def errors(number):
    return [np.random.uniform(-1,1,1)[0] for i in range(number)]

err = errors(6)

Now we can compute y.

In [23]:
np.dot(designMatrix, mu) + err

array([ 18.91185505,  18.71176511,  19.29942917,  19.30368338,
       -12.72612184, -12.3980189 ])

### Misc - might need this later

In [24]:
""" generate a matrix of r rows by c columns with o observations per cell between lower and upper """
def spawnMatrix(nRow, nCol, cellSize, cellLower, cellUpper):
    return pd.DataFrame(
        [
            [np.array(list(random.randint(cellLower, cellUpper)
                for i in range(cellSize)))                         
                    for i in range(nRow)
            ]
            for i in range(nCol)
        ]
    ).transpose()

# create values for y using the above function
y = spawnMatrix(nRow = 6, nCol = 6, cellSize = 3, cellLower = 1, cellUpper = 10)

# name the columns for convinience during iteration
y.columns = ["col" + str(i) for i in range(6)]

print("The matrix for y\n", y, "\n")

print("The design matrix transposed is:\n", designMatrix.transpose().values, "\n")
for row in y.itertuples():
    print("The y value is:", row.col0)
    print("The product with the matrix is:", np.dot(row.col0, designMatrix.transpose()), "\n")

The matrix for y
          col0        col1         col2        col3        col4         col5
0   [7, 4, 2]   [2, 2, 8]  [10, 3, 10]   [4, 4, 9]  [10, 3, 6]  [7, 10, 10]
1   [1, 9, 4]   [5, 2, 9]   [10, 7, 9]   [2, 3, 3]   [1, 7, 3]    [8, 9, 8]
2   [7, 1, 5]   [1, 3, 1]    [9, 1, 3]   [9, 5, 1]   [4, 1, 8]    [9, 9, 9]
3   [7, 1, 7]   [4, 9, 8]    [6, 3, 4]  [10, 7, 4]   [1, 3, 5]    [8, 9, 5]
4   [7, 9, 7]  [10, 3, 6]    [2, 7, 4]  [3, 8, 10]   [8, 2, 9]    [4, 8, 2]
5  [1, 10, 2]   [7, 2, 3]    [9, 8, 7]  [9, 7, 10]   [9, 9, 8]   [1, 5, 10] 

The design matrix transposed is:
 [[ 1  1  1  1  1  1]
 [ 1  1  0  0 -1 -1]
 [ 0  0  1  1 -1 -1]] 

The y value is: [7 4 2]
The product with the matrix is: [11 11  9  9  1  1] 

The y value is: [1 9 4]
The product with the matrix is: [ 10  10   5   5 -12 -12] 

The y value is: [7 1 5]
The product with the matrix is: [ 8  8 12 12  1  1] 

The y value is: [7 1 7]
The product with the matrix is: [ 8  8 14 14 -1 -1] 

The y value is: [7 9 7]
The pr