In [1]:
import pandas as pd
import numpy as np
import random

First we would need some values for mu. We'll use whatever.

In [2]:
# random values for mu
mu = [9, 10 ,11]
mu

[9, 10, 11]

We will also need to generate some matrices for y, and they'll need to contain cells of n number of observation in each cell.

col0         col1        col2        col3        col4        col5
0   [1, 4, 3]    [1, 6, 4]  [3, 10, 8]   [3, 8, 2]   [5, 7, 6]   [6, 7, 4]
1   [7, 9, 2]    [1, 1, 4]   [3, 1, 6]   [8, 7, 7]   [2, 8, 2]  [4, 10, 4]
2  [2, 10, 4]    [3, 4, 2]  [10, 7, 9]   [3, 5, 1]   [3, 6, 5]   [1, 9, 4]
3   [4, 8, 1]    [4, 8, 9]   [2, 3, 3]  [9, 6, 10]   [9, 8, 4]   [5, 7, 6]
4   [6, 4, 8]   [9, 10, 9]  [2, 10, 4]  [10, 1, 7]  [4, 9, 10]   [5, 8, 4]
5   [3, 3, 1]  [10, 7, 10]   [1, 5, 2]   [1, 6, 5]   [2, 7, 3]   [6, 3, 7]

We now have a 6x6 matrix or cells the each contain 3 values. This will be easier; we can just frame some lists.

In [4]:
# create a design matrix (from the notes)
designMatrix = pd.DataFrame(
    [
        np.array([1, 1, 1, 1, 1, 1]),
        np.array([1, 1, 0, 0, -1, -1]),
        np.array([0, 0, 1, 1, -1, -1])
    ]
).transpose()

# inspect to make sure it is ok
print(designMatrix.values)

[[ 1  1  0]
 [ 1  1  0]
 [ 1  0  1]
 [ 1  0  1]
 [ 1 -1 -1]
 [ 1 -1 -1]]


This looks likes the design matrix presented in the notes. Next up is the errors.

In [95]:
# we will use random decimal values between -1, 1
def errors(number):
    return [np.random.uniform(-1,1,1)[0] for i in range(number)]

err = errors(6)

Now we can compute y.

In [99]:
np.dot(designMatrix, mu) + err

array([ 19.34813815,  18.51890787,  19.22691646,  19.88904498,
       -11.61824228, -11.1934337 ])

### Misc - might need this later

In [96]:
""" generate a matrix of r rows by c columns with o observations per cell between lower and upper """
def spawnMatrix(nRow, nCol, cellSize, cellLower, cellUpper):
    return pd.DataFrame(
        [
            [np.array(list(random.randint(cellLower, cellUpper)
                for i in range(cellSize)))                         
                    for i in range(nRow)
            ]
            for i in range(nCol)
        ]
    ).transpose()

# create values for y using the above function
y = spawnMatrix(nRow = 6, nCol = 6, cellSize = 3, cellLower = 1, cellUpper = 10)

# name the columns for convinience during iteration
y.columns = ["col" + str(i) for i in range(6)]

print("The matrix for y\n", y, "\n")

print("The design matrix transposed is:\n", designMatrix.transpose().values, "\n")
for row in y.itertuples():
    print("The y value is:", row.col0)
    print("The product with the matrix is:", np.dot(row.col0, designMatrix.transpose()), "\n")

The matrix for y
          col0        col1        col2        col3        col4        col5
0   [2, 4, 2]   [3, 9, 3]   [7, 7, 7]   [8, 4, 5]  [8, 3, 10]  [7, 10, 5]
1   [6, 1, 3]  [7, 4, 10]  [4, 6, 10]  [8, 10, 6]   [1, 5, 6]  [1, 5, 10]
2   [4, 6, 5]   [2, 5, 1]   [1, 3, 7]   [4, 3, 7]   [3, 8, 4]  [3, 10, 5]
3   [8, 9, 8]   [9, 7, 9]   [5, 9, 2]   [9, 8, 4]  [10, 7, 5]  [5, 10, 9]
4  [9, 4, 10]   [3, 2, 6]   [6, 2, 6]  [6, 5, 10]   [6, 9, 6]  [9, 10, 7]
5   [4, 5, 6]   [7, 6, 2]   [7, 6, 6]   [3, 4, 5]  [7, 9, 10]  [2, 10, 7] 

The design matrix transposed is:
 [[ 1  1  1  1  1  1]
 [ 1  1  0  0 -1 -1]
 [ 0  0  1  1 -1 -1]] 

The y value is: [2 4 2]
The product with the matrix is: [ 6  6  4  4 -4 -4] 

The y value is: [6 1 3]
The product with the matrix is: [7 7 9 9 2 2] 

The y value is: [4 6 5]
The product with the matrix is: [10 10  9  9 -7 -7] 

The y value is: [8 9 8]
The product with the matrix is: [17 17 16 16 -9 -9] 

The y value is: [ 9  4 10]
The product with the matrix i